#!/usr/bin/env python3
# [skill: go-team-standards · dev-dna] 构建可离线加载的安全题库

import argparse
import json
import os
import tempfile
from pathlib import Path

if __package__:
    from .extract_questions import extract_questions, validate_questions
else:
    from extract_questions import extract_questions, validate_questions


_ALL_IDS = list(range(1, 101))
_SUPPLEMENTED_IDS = {73, 89, 90}
_ARCHIVE_IDS = [
    question_id
    for question_id in _ALL_IDS
    if question_id != 73
]
_GENERATED_COMMENT = (
    "// [skill: go-team-standards · dev-dna] "
    "生成可离线加载的安全题库\n"
    "// Generated by scripts/build_questions.py; do not edit."
)

_QUESTION_73 = "Go 中值接收者和指针接收者有什么区别？"
_ANSWER_73 = (
    "<p><strong>补充整理：</strong>"
    "值接收者接收的是值的副本，方法内的修改不能直接修改原值；"
    "指针接收者可以修改其指向的值，并避免复制大型结构体。</p>"
    "<p>方法集规则是：T 的方法集只包含接收者为 T 的方法；"
    "*T 的方法集同时包含接收者为 T 和 *T 的方法。"
    "对可寻址值的方法调用，编译器可以自动取地址，"
    "但这不会改变接口方法集规则。</p>"
    "<p>当修改状态、复制成本或方法集语义有要求时，"
    "应统一使用指针接收者。</p>"
)
_ANSWER_89 = (
    "<p><strong>补充整理：</strong>"
    "先用 <code>pprof</code> 和基准测试的 <code>-benchmem</code> "
    "数据定位问题，再减少不必要的分配和存活引用。</p>"
    "<p>为可预估容量的 <code>slice</code>、<code>map</code> 和 "
    "<code>strings.Builder</code> 预分配空间，"
    "避免无谓的类型转换和堆逃逸；大数据应采用流式处理，"
    "避免一次性驻留内存。</p>"
    "<p><code>sync.Pool</code> 只应用于生命周期短、"
    "可安全重置的临时复用对象；每次修改后都要重新运行基准测试，"
    "确认收益和副作用。</p>"
)
_ANSWER_90 = (
    "<p><strong>补充整理：</strong>"
    "先降低分配速率和存活堆大小，再用 <code>pprof</code> "
    "与运行时 GC 指标观察暂停、频率、CPU 和内存。</p>"
    "<p>只有证据表明需要时才调整 <code>GOGC</code> 和 "
    "<code>GOMEMLIMIT</code>；不要在请求路径调用 "
    "<code>runtime.GC()</code>，因为强制 GC 通常增加延迟和 CPU 开销。</p>"
    "<p>调参必须理解 CPU 与内存之间的权衡，"
    "并在接近生产的负载下压测后再采用。</p>"
)


def _validate_archive_shape(questions):
    if not isinstance(questions, list):
        raise ValueError("提取结果必须是列表")

    ids = [
        item.get("id") if isinstance(item, dict) else None
        for item in questions
    ]
    if ids != _ARCHIVE_IDS:
        raise ValueError(
            "源文章题号必须按顺序包含 1..100 且仅缺少 73"
        )

    for item in questions:
        question_id = item["id"]
        if question_id in {89, 90}:
            if not isinstance(item.get("question"), str):
                raise ValueError(
                    "源文章题号 {} 的问题格式错误".format(question_id)
                )
            if not item["question"].strip():
                raise ValueError(
                    "源文章题号 {} 的问题为空".format(question_id)
                )
            answer = item.get("answerHtml")
            if not isinstance(answer, str) or answer.strip():
                raise ValueError(
                    "源文章题号 {} 应当只有问题、没有答案".format(
                        question_id
                    )
                )


def _validate_sources(questions):
    supplemented = set()
    for item in questions:
        question_id = item["id"]
        expected_source = (
            "supplemented"
            if question_id in _SUPPLEMENTED_IDS
            else "zhihu-archive"
        )
        if item.get("source") != expected_source:
            raise ValueError(
                "题号 {} 的来源标签应为 {}".format(
                    question_id,
                    expected_source,
                )
            )
        if item["source"] == "supplemented":
            supplemented.add(question_id)

    if supplemented != _SUPPLEMENTED_IDS:
        raise ValueError("补充题号必须且只能是 73、89、90")


def _validate_built_questions(questions):
    validate_questions(questions)
    _validate_sources(questions)


def build_questions(source_html: str) -> list[dict]:
    """Return exactly 100 validated question records with source metadata."""
    archive_questions = extract_questions(source_html)
    _validate_archive_shape(archive_questions)
    archive_by_id = {
        item["id"]: item
        for item in archive_questions
    }

    questions = []
    for question_id in _ALL_IDS:
        if question_id == 73:
            question = _QUESTION_73
            prompt_html = ""
            answer_html = _ANSWER_73
        else:
            archive_record = archive_by_id[question_id]
            question = archive_record["question"]
            prompt_html = archive_record["promptHtml"]
            if question_id == 89:
                answer_html = _ANSWER_89
            elif question_id == 90:
                answer_html = _ANSWER_90
            else:
                answer_html = archive_record["answerHtml"]

        questions.append(
            {
                "id": question_id,
                "question": question,
                "promptHtml": prompt_html,
                "answerHtml": answer_html,
                "source": (
                    "supplemented"
                    if question_id in _SUPPLEMENTED_IDS
                    else "zhihu-archive"
                ),
            }
        )

    _validate_built_questions(questions)
    return questions


def render_questions_js(questions: list[dict]) -> str:
    """Return deterministic JavaScript assigning window.GO_INTERVIEW_QUESTIONS."""
    _validate_built_questions(questions)
    records = [
        {
            "id": item["id"],
            "question": item["question"],
            **(
                {"promptHtml": item["promptHtml"]}
                if item.get("promptHtml")
                else {}
            ),
            "answerHtml": item["answerHtml"],
            "source": item["source"],
        }
        for item in questions
    ]
    payload = json.dumps(
        records,
        ensure_ascii=False,
        indent=2,
    )
    payload = payload.replace("\u2028", "\\u2028")
    payload = payload.replace("\u2029", "\\u2029")
    return (
        "{}\n"
        "window.GO_INTERVIEW_QUESTIONS = Object.freeze(\n"
        "{}\n"
        ");\n"
    ).format(_GENERATED_COMMENT, payload)


def _atomic_write_text(output_path, content):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        dir=str(output_path.parent),
        prefix=".{}.".format(output_path.name),
        suffix=".tmp",
    )
    try:
        with os.fdopen(
            file_descriptor,
            "w",
            encoding="utf-8",
            newline="\n",
        ) as temporary_file:
            temporary_file.write(content)
            temporary_file.flush()
            os.fsync(temporary_file.fileno())
        os.replace(temporary_name, output_path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def _main():
    argument_parser = argparse.ArgumentParser(
        description=(
            "Build a validated JavaScript question dataset from an HTML file."
        )
    )
    argument_parser.add_argument("source_html", type=Path)
    argument_parser.add_argument("output_js", type=Path)
    args = argument_parser.parse_args()

    source_html = args.source_html.read_text(encoding="utf-8")
    questions = build_questions(source_html)
    _atomic_write_text(
        args.output_js,
        render_questions_js(questions),
    )
    print("built 100 questions: 1..100")


if __name__ == "__main__":
    _main()
